name: task_management_app
description: A Flutter task management application with authentication and local storage.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase packages
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^5.6.5
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  # UI components
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  # Form validation
  formz: ^0.6.0
  # Utilities
  uuid: ^3.0.7
  logger: ^2.0.1
  # Push notifications
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.2
  timezone: ^0.9.4
  flutter_launcher_icons: ^0.14.3
  connectivity_plus: ^6.1.3
  table_calendar: ^3.0.9
  rxdart: ^0.27.7
  get_it: ^8.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.3
  mockito: ^5.4.2



flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/animations/